language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install codecov pytest pytest-cov
  - pip install git+https://github.com/Sauci/pyelf.git@$TRAVIS_BRANCH
after_success:
  - codecov
script:
  - py.test --cov-report html --cov pyelf --verbose --cov-config=.coveragerc
